[package]
name = "rmsd-yaml-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.rmsd_yaml]
path = ".."

[[bin]]
name = "from_str"
path = "fuzz_targets/from_str.rs"
test = false
doc = false
bench = false

[[bin]]
name = "from_reader"
path = "fuzz_targets/from_reader.rs"
test = false
doc = false
bench = false
