name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - base

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Check fmt
      run: cargo fmt -- --check

    - name: Check clippy
      run: cargo clippy -- -D warnings

  integ:
    name: integ
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust_version: "stable"
          - rust_version: "beta"
          - rust_version: "nightly"

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust_version }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust_version }}
          override: true
          components: rustfmt

    - name: Update repositories
      run: sudo apt-get -y update

    - name: Build
      run: cargo build --verbose --all

    - name: Run cargo tests
      run: cargo test -- --show-output
